# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Chutney Testing
site_url: https://www.chutney-testing.com/
site_description: Opinionated test tool for Specification by Example
site_author: Chutney Testing Team
repo_name:
repo_url: https://github.com/chutney-testing/chutney/
edit_uri: https://github.com/chutney-testing/chutney-testing.github.io/docs

nav:
  - Getting Started: getting_started.md
  - Documentation:
    - Installation: install.md
    - Configuration:
      - environment: configuration/env.md
      - roles: configuration/roles.md
      - agent: configuration/agent.md
    - 'Write a scenario': write.md
    - Actions:
        - http: actions/http.md
        - amqp: actions/amqp.md
  - Concepts: concepts.md
  - About: about.md

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.svg
  language: en
  font:
    text: Ubuntu
    #text: Montserrat
    code: Source Code Pro

# Material theme specific
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: FranÃ§ais
      link: /fr/
      lang: fr
    - name: ä¸­æ–‡
      link: /zh/
      lang: zh

markdown_extensions:
  - toc:
      permalink: "ðŸ”—"
      baselevel: 2
