# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Chutney Testing
site_url: https://www.chutney-testing.com/

nav:
  - Getting Started: getting_started.md
  - Documentation:
    - Installation: install.md
    - Configuration:
      - environment: configuration/env.md
      - agent: configuration/agent.md
      - roles: configuration/roles.md
    - 'Write a scenario': write.md
    - Actions:
        - http: actions/http.md
        - amqp: actions/amqp.md
  - Concepts: concepts.md
  - About: about.md

theme:
  name: material
  favicon: img/favicon.ico
  language: en
  font:
    text: Ubuntu
    #text: Montserrat
    code: Source Code Pro

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Français
      link: /fr/
      lang: fr
    - name: 中文
      link: /zh/
      lang: zh
